"""first migrate

Revision ID: c55913c40bfb
Revises: 
Create Date: 2022-04-27 22:29:45.247027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c55913c40bfb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquery', sa.Text(), nullable=True),
    sa.Column('option_0', sa.String(length=128), nullable=True),
    sa.Column('option_1', sa.String(length=128), nullable=True),
    sa.Column('option_2', sa.String(length=128), nullable=True),
    sa.Column('option_3', sa.String(length=128), nullable=True),
    sa.Column('answer', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    # ### end Alembic commands ###
